image: node:16

pipelines:
    pull-requests:
        '**':
            - step:
                  name: Install
                  script:
                      - npm install -g typescript
                      - npm install
            - step:
                  name: Build
                  script:
                      - npm run build
